apiVersion: v1
kind: Service
metadata:
  name: sample-be-service
  labels:
    app: sample-be-app
spec:
  selector:
    app: sample-be-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
